version: '2'

services:
  cadcam-api:
    build:
      context: ./src/
      dockerfile: api/Dockerfile
    image: cadcam-api:latest
    container_name: cadcam-api
    ports:
      - 5000:5000  
    volumes:
      - ./src/:/srv/src/
    environment:
      - ENVIRONMENT=dev
    links:
      - postgres:local-cadcam-postgres.aveng.us

  cadcam-buildui:
    build:
      context: ./src/
      dockerfile: ui/Dockerfile
    image: cadcam-ui:latest
    container_name: cadcam-buildui
    volumes:
      - ./data/:/srv/data
      - ./src/:/srv/src
    environment:
      - ENVIRONMENT=dev
    ports:
      - 3000:3000

  postgres:
    image: postgres:10.8
    restart: always
    environment:
      - POSTGRES_DB=cadcam
      - POSTGRES_USER=wombat
      - POSTGRES_PASSWORD=1wombat2
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
